import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FlaskConical, Printer, RefreshCw, ShieldCheck } from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { useRules } from '@/hooks/useRules';
import {
  useModelMonitoring, useModelPromotions, useModelStatus, useModelVersions, useRequestRetrain,
  useRequestRollback, useTrainingJobs,
} from '@/hooks/useModelGovernance';
import { useAuth } from '@/contexts/AuthContext';
import { canTrainModel } from '@/lib/permissions';
import { ModelWorkflowPanel } from '@/components/model/ModelWorkflowPanel';
import { ReasonDialog } from '@/components/model/ReasonDialog';
import { ModelCardTab } from '@/components/model/ModelCardTab';
import { ValidationTab } from '@/components/model/ValidationTab';
import { MonitoringTab } from '@/components/model/MonitoringTab';
import { VersionHistoryTab, VersionStatusBadge } from '@/components/model/VersionHistoryTab';
import { formatPct } from '@/components/model/format';

export function SyntheticDataNotice({ share }: { share: number | null | undefined }) {
  if (!share) return null;
  return (
    <Alert className="border-status-warning/40">
      <FlaskConical className="h-4 w-4 text-status-warning" />
      <AlertDescription>
        <strong>Demonstration data.</strong> {formatPct(share)} of scored alerts were generated by the synthetic
        data seeder, and their investigator outcomes are simulated. The figures show how this page works; they do
        not describe a real model's performance.
      </AlertDescription>
    </Alert>
  );
}

export default function ModelGovernancePage() {
  const { data: status, isLoading: statusLoading } = useModelStatus();
  const { data: versions = [], isLoading: versionsLoading } = useModelVersions();
  const { data: monitoring } = useModelMonitoring();
  const { data: rules } = useRules();
  const { data: jobs = [] } = useTrainingJobs();
  const { data: promotions = [] } = useModelPromotions();
  const { user } = useAuth();
  const retrain = useRequestRetrain();
  const rollback = useRequestRollback();
  const [selected, setSelected] = useState<string>('');
  const [tab, setTab] = useState('card');
  const [retrainOpen, setRetrainOpen] = useState(false);
  const [rollbackVersion, setRollbackVersion] = useState<string | null>(null);

  const latestJob = jobs[0];
  const pending = promotions.find((p) => p.status === 'PENDING');
  const blockedReason =
    latestJob && (latestJob.status === 'QUEUED' || latestJob.status === 'RUNNING')
      ? 'A retrain is already queued or running.'
      : pending
        ? `${pending.version} is awaiting a Principal Officer's decision.`
        : null;
  const mayTrain = canTrainModel(user);

  useEffect(() => {
    if (!selected && status?.activeVersion) setSelected(status.activeVersion.version);
  }, [selected, status]);

  const active = status?.activeVersion;

  return (
    <AppLayout>
      <div className="space-y-6 animate-fade-in">
        <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
          <div className="space-y-1">
            <h1 className="flex items-center gap-2 text-2xl font-bold">
              <ShieldCheck className="h-6 w-6 text-primary" />
              Model Governance
            </h1>
            <p className="text-muted-foreground">
              What the alert-prioritisation model is, how it was validated, how it performs against investigator
              decisions, and every change made to it.
            </p>
          </div>
          <div className="flex shrink-0 items-center gap-3">
            {active && (
              <div className="flex items-center gap-2 whitespace-nowrap text-sm">
                <span className="text-muted-foreground">Active</span>
                <span className="font-mono font-medium">{active.version}</span>
                <VersionStatusBadge status={active.status} />
              </div>
            )}
            {mayTrain && (
              <Button size="sm" disabled={!!blockedReason} title={blockedReason ?? undefined}
                      onClick={() => setRetrainOpen(true)}>
                <RefreshCw className="mr-2 h-4 w-4" />
                Request retrain
              </Button>
            )}
            <Button variant="outline" size="sm" asChild>
              <Link to="/ml-status/print" target="_blank">
                <Printer className="mr-2 h-4 w-4" />
                Print report
              </Link>
            </Button>
          </div>
        </div>

        <SyntheticDataNotice share={monitoring?.syntheticShare} />

        <ModelWorkflowPanel
          latestJob={latestJob}
          pending={pending}
          versions={versions}
          activeVersion={active?.version}
          onReview={(v) => { setSelected(v); setTab('validation'); }}
        />

        {statusLoading || versionsLoading || !status ? (
          <Skeleton className="h-96" />
        ) : (
          <Tabs value={tab} onValueChange={setTab} className="space-y-6">
            <TabsList>
              <TabsTrigger value="card">Model card</TabsTrigger>
              <TabsTrigger value="validation">Validation</TabsTrigger>
              <TabsTrigger value="monitoring">Monitoring</TabsTrigger>
              <TabsTrigger value="history">Version history</TabsTrigger>
            </TabsList>
            <TabsContent value="card"><ModelCardTab status={status} rules={rules} /></TabsContent>
            <TabsContent value="validation">
              <ValidationTab versions={versions} selected={selected} onSelect={setSelected} />
            </TabsContent>
            <TabsContent value="monitoring"><MonitoringTab /></TabsContent>
            <TabsContent value="history">
              <VersionHistoryTab
                versions={versions}
                promotions={promotions}
                rollback={mayTrain ? { blockedReason, onRequest: setRollbackVersion } : undefined}
              />
            </TabsContent>
          </Tabs>
        )}

        <ReasonDialog
          open={retrainOpen}
          onOpenChange={setRetrainOpen}
          title="Request a model retrain"
          description={<>
            The training worker builds a new candidate from all labelled alerts and validates it. It does not go
            live until a Principal Officer approves it. Your reason is recorded in the audit trail.
          </>}
          label="Why retrain now?"
          placeholder="e.g. 120 new investigator decisions since the last version; quarterly model review."
          confirmLabel="Request retrain"
          pending={retrain.isPending}
          onConfirm={(reason) => retrain.mutate(reason, { onSuccess: () => setRetrainOpen(false) })}
        />
        <ReasonDialog
          open={rollbackVersion !== null}
          onOpenChange={(o) => !o && setRollbackVersion(null)}
          title={`Request rollback to ${rollbackVersion ?? ''}`}
          description={<>
            {rollbackVersion} becomes live again only after a Principal Officer approves the rollback. Alerts already
            scored keep their scores. Your reason is recorded in the audit trail.
          </>}
          label="Why roll back?"
          placeholder="e.g. Since the last promotion, investigators are dismissing far more HIGH alerts."
          confirmLabel="Request rollback"
          pending={rollback.isPending}
          onConfirm={(reason) => rollback.mutate(
            { version: rollbackVersion!, reason },
            { onSuccess: () => setRollbackVersion(null) },
          )}
        />
      </div>
    </AppLayout>
  );
}
